# Generated by Django 5.0.3 on 2024-03-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_payment_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, default='./static/images/fun-3d-cartoon-illustration-indian-doctor.jpg', null=True, upload_to=''),
        ),
    ]
