# Generated by Django 5.0.3 on 2024-03-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_appointment_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='name',
        ),
    ]
