# Generated by Django 5.0.3 on 2024-03-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_patient_appointment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='name',
            new_name='patient_id',
        ),
    ]
