# Generated by Django 5.0.3 on 2024-04-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_doctor_is_active_doctor_last_login_doctor_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
