# Generated by Django 5.0.3 on 2024-04-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_doctor_is_active_remove_doctor_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='is_staff',
        ),
    ]
