# Generated by Django 5.0.3 on 2024-04-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_doctor_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
    ]
