# Generated by Django 5.0.3 on 2024-04-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_doctor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
